### ISSUE TITLE
ControllerAs syntax

### ISSUE THREAD

**Issue by MilosStanic** [Urigo/meteor-angular-socially#22]
Hi @Urigo ,

As I said, I tried redoing the example with controllerAs syntax as suggested by John Papa's style guide. 
However, the reactive part doesn't seem to work. Also the pagination doesn't work. 

Please take a look at my fork of this repo with controllerAs branch, here: 
https://github.com/MilosStanic/meteor-angular-socially/tree/controllerAs

The files of consideration are: 
client/parties/controllers/partiesList.js
client/parties/controllers/partyDetails.js
client/parties/views/parties-list.ng.html
client/parties/views/party-details.ng.html
client/routes.js

It would really be nice if it can be made to work with controllerAs syntax. 

Thanks

**Comment by Urigo** [comment]
OK I will have a look tomorrow and hopefully solve it.

But let's separate that from the material design because I want to quickly add your implementation as chapter 18 of the tutorial, it's really cool and I know a lot of people are looking forward to it.

I also definitely want to add a controllerAs to the tutorial right after that

**Comment by Urigo** [comment]
OK I've looked at your code.
1. When using getReactively, have you tried 'perPage' instead of 'vm.perPage'?
2. When using $watch with controllerAs - http://stackoverflow.com/questions/24078535/angularjs-controller-as-syntax-and-watch
Tell me if that helped

**Comment by MilosStanic** [comment]
Oh, I forgot to answer this. Yes, I tried every possible variant, and it doesn't work.

**Comment by Urigo** [comment]
Can you have a look at the code for the Angular2.0Now socially?
https://github.com/pbastowski/meteor-angular-socially/tree/feature/ng2now
I think he used the controllerAs syntax there

**Comment by Urigo** [comment]
Closing as it solved in https://github.com/pbastowski/meteor-angular-socially/tree/feature/ng2now

Soon we will add this branch as a parallel tutorial

**Comment by Amalthean** [comment]
Does this mean that this works only for Angular2.0Now ?

**Comment by Amalthean** [comment]
Does that mean that `getReactively()` when using`controllerAs` syntax works only for Angular2.0Now?

I still get `options` object in  `"parties"` publication as `{ limit: NaN, skip: NaN }` when reactively subscribing from partiesList.js controller and therefore mongo query does not work properly within the publication.

**Comment by Urigo** [comment]
@Amalthean no, the nice thing about Angular2.0Now is that it doesn't have any difference from Angular 1.0 and everything that works there works on Angular 1.0 as well.

To use `getReactively` with controllerAs you should call it like that:

```
$scope.getReactively('vm.sort')
```

(just like using $watch with controllerAs)

You can also see more examples (that @MilosStanic wrote) in our API docs here:
http://angular-meteor.com/api/getReactively#example2controllerassyntax

Hope it helps

**Comment by Amalthean** [comment]
@Urigo thank you for your fast response. I cloned @MilosStanic 's controllerAs branch and tested .. and it seems that controllerAs syntax is not working properly. When I log `options` object inside server publication I still get  `options  = { limit: NaN, skip: NaN }` and therefore the pager does not work propperly.

**Comment by Urigo** [comment]
I've created a new brach from step 12 - https://github.com/Urigo/meteor-angular-socially/tree/step_12_controller_as_vm

Let me know if that helped

**Comment by Amalthean** [comment]
@Urigo thanks again it certainly helped. 
In @MilosStanic 's controllerAs branch he is naming  `controllerAs='plc'` (routes.js file) and in partiesList.js he is subscribing with `$scope.getReactively('vm.page')`,`$scope.getReactively('vm.sort')` and `$scope.getReactively('vm.perPage')` therefore when subscribing to `'parties'` publication (server/parties.js file) options object gets `{limit: NaN, skip: NaN}` . 
Actually `$scope.getReactively()` needs to be used with the same prefix as in controllerAs in routes.js ... `$scope.getReactively('plc.page')`,`$scope.getReactively('plc.sort')` and `$scope.getReactively('plc.perPage')`

**Comment by MilosStanic** [comment]
@Amalthean 
Yeah, the `getReactively()` didn't work for me with `controller-as` syntax, and I tried every possible combination except `$scope.getReactively('plc.page')` :) . If that is the syntax that works, it's good to know. It should make way to the tutorials.
