### ISSUE TITLE
Stuck at step 1

### ISSUE THREAD

**Issue by aspiringpro** [Urigo/meteor-angular-socially#5]
I'm stuck at step 1!

No text is displaying for me at all now.

**Comment by aspiringpro** [comment]
WARNING: Tried to load angular more than once.

**Comment by Urigo** [comment]
@aspiringpro The tutorial is updated to the new urigo:angular@0.6.0-alpha version.

Please make sure you updated the version (it is not happening automatically now because it's alpha, we will soon ship the official version).

Let me know if it worked

**Comment by eighteyes** [comment]
@Urigo if you follow the tutorial to the letter you don't load the new alpha version, you load 0.5.11

A little clarity regarding version documentation would be nice.

**Comment by Urigo** [comment]
Now that we released the new 0.6.0 version it should be OK :)

**Comment by remainstheday** [comment]
I am in version 0.7.1 and still getting WARNING: Tried to load angular more than once.

**Comment by Urigo** [comment]
@trentontri make sure that all your angular html files ends with .ng.html  (and all the paths as well)

tell me if it worked

**Comment by remainstheday** [comment]
@Urigo I changed the html files as you mentioned the problem for me seems to be with ui.router and the placement of `<div ui-view></div>` I have fixed the errors but cannot get ui-router to load a template. You can view my source code at github.com/trentontri/trinet

**Comment by Urigo** [comment]
@trentontri fixed in the fork here:
https://github.com/trentontri/trinet/pull/1

What did I do:
1. Remove the onReady initialization.  if you have ng-app you don't need that.
2. add this line  'angular.module ('trinet').run(function($state){});'  because of this: https://github.com/angular-ui/ui-router/issues/679
3. Renamed singup.ng.html to signup.ng.html  (use had a spelling mistake)
